config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root "users#index"

  resources :users, only: [:show, :index]
  resources :tests, only: [:new, :create, :show, :index]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
	has_one :questions
	has_many :answer_users
end

app/models/answer_user.rb
class AnswerUser < ApplicationRecord
	has_one :answer_options
	has_one :passed_tests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/passed_test.rb
class PassedTest < ApplicationRecord
	has_one :users
	has_one :tests
	has_many :answer_users
end

app/models/question.rb
class Question < ApplicationRecord
	has_one :tests
	has_many :answer_options
end

app/models/star.rb
class Star < ApplicationRecord
	has_one :users
	has_one :tests
end

app/models/test.rb
class Test < ApplicationRecord
	has_one :users
	has_many :questions
	has_many :stars
	has_many :passed_tests

	def author
		User.find(self.user_id)
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tests
  has_many :passed_tests
  has_many :stars
  has_secure_password
  validates :password, length: { minimum: 6 },
                       presence: true

  def become_author 
    self.update_attribute :is_author, true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	def new
		@test = Test.new
	end
	def create
		@test = Test.new( test_params )
    @test.save
    redirect_to @test
	end
	def test_params
		params.require(:test).permit(:name)
	end
  def index
    @tests = Test.all.where("user_id = 9")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def create
  end

  def show
    @user = User.find(params[:id])
  end
  def index
    @users = User.all
  end
  def edit
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TauEst</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<li>
		<span><%= user.id %></span> | 
		<span><%= link_to user.name, user %> </span>, 
		<span><%= user.is_author %></span> 
	</li>	
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1><%= @user.name + " | " + @user.email%> </h1>

<% if @user.is_author %>
	<%= link_to 'create new test', new_test_path %>	
<% end %>